%YAML:1.0
################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

BaseConfig:
  minDetectorConfidence: 0.2    # If the confidence of a detector bbox is lower than this, then it won't be considered for tracking

TargetManagement:
  enableBboxUnClipping: 1       # In case the bbox is likely to be clipped by image border, unclip bbox
  maxTargetsPerStream: 99       # Max number of targets to track per stream. Recommended to set >10. Note: this value should account for the targets being tracked in shadow mode as well. Max value depends on the GPU memory capacity

  # [Creation & Termination Policy]
  minIouDiff4NewTarget: 0.5     # If the IOU between the newly detected object and any of the existing targets is higher than this threshold, this newly detected object will be discarded.
  minTrackerConfidence: 0.2     # If the confidence of an object tracker is lower than this on the fly, then it will be tracked in shadow mode. Valid Range: [0.0, 1.0]
  probationAge: 3               # If the target's age exceeds this, the target will be considered to be valid.
  maxShadowTrackingAge: 30      # Max length of shadow tracking. If the shadowTrackingAge exceeds this limit, the tracker will be terminated.
  earlyTerminationAge: 1        # If the shadowTrackingAge reaches this threshold while in TENTATIVE period, the target will be terminated prematurely.

DataAssociation:
  dataAssociatorType: 0         # the type of data associator among { DEFAULT= 0 }
  associationMatcherType: 0     # the type of matching algorithm among { GREEDY=0, CASCADED=1 }
  checkClassMatch: 1            # If checked, only the same-class objects are associated with each other. Default: true

  # [Association Metric: Thresholds for Valid Candidates]
  minMatchingScore4Overall: 0.0 # Min total score
  minMatchingScore4SizeSimilarity: 0.6    # Min bbox size similarity score
  minMatchingScore4Iou: 0.1     # Min IOU score
  minMatchingScore4VisualSimilarity: 0.2  # Min visual similarity score

  # [Association Metric: Weights]
  matchingScoreWeight4VisualSimilarity: 0.6  # Weight for the visual similarity (in terms of correlation response ratio)
  matchingScoreWeight4SizeSimilarity: 0.0    # Weight for the Size-similarity score
  matchingScoreWeight4Iou: 0.4               # Weight for the IOU score
  matchingScoreWeight4Age: 0.0               # Weight for the tracker age

StateEstimator:
  stateEstimatorType: 1         # the type of state estimator among { DUMMY=0, SIMPLE=1, REGULAR=2 }

  # [Dynamics Modeling]
  processNoiseVar4Loc: 2.0      # Process noise variance for bbox center
  processNoiseVar4Size: 1.0     # Process noise variance for bbox size
  processNoiseVar4Vel: 0.1      # Process noise variance for velocity
  measurementNoiseVar4Detector: 4.0    # Measurement noise variance for detector bbox
  measurementNoiseVar4Tracker: 16.0    # Measurement noise variance for tracker bbox

VisualTracker:
  visualTrackerType: 1          # the type of visual tracker among { DUMMY=0, NvDCF=1, NvDeepSORT=2 }

  # [NvDCF]
  useColorNames: 1              # Use ColorNames feature
  useIbp: 1                     # Use IBP feature
  useHist: 1                    # Use Hist feature
  histBinNum: 16                # Hist bin number
  template_size: 80             # Template size
  search_size: 320              # Search size
  featureImgSizeLevel: 3        # Size of a feature image. Valid range: {1, 2, 3, 4, 5}. From smallest to largest
  SearchRegionPaddingScale: 1   # Search region padding scale
  distWeightScale: 0.8          # Distance weight scale for the NvDCF tracker
  maxTemplateSize: 80           # Max template size
  minTemplateSize: 10           # Min template size
  templateBaddrThreshold: 0.03  # Template update threshold. Update template when the template gets older
  templateUpdateRate: 0.1       # Template update rate. How much to update the template at once